In [41]:
import json
import numpy as np
import pandas as pd
from pprint import pprint

#first, load the data in. (from previous 4 seasons)
with open('2018_19seasondata.json') as f:
    data4 = json.load(f)
with open('2017_18seasondata.json') as f:
    data3 = json.load(f)
with open('2016_17seasondata.json') as f:
    data2 = json.load(f)
with open('2015_16seasondata.json') as f:
    data1 = json.load(f)
with open('SeasonData2014-15.json') as f:
    data5 = json.load(f)
with open('SeasonData2013-14.json') as f:
    data6 = json.load(f)
with open('SeasonData2012-13.json') as f:
    data7 = json.load(f)
with open('SeasonData2011-12.json') as f:
    data8 = json.load(f)


#lets get a list of just all the arsenal games.

arsenal_games = []

for game in data1:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)
for game in data2:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)
for game in data3:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)
for game in data4:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)
for game in data5:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)
for game in data6:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)
for game in data7:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)
for game in data8:
    if game['HomeTeam'] == 'Arsenal' or game['AwayTeam'] == 'Arsenal':
        arsenal_games.append(game)


#the columns we are focused on are hometeam, awayteam, scores, halftime scores (for fun- will c),referee.. will manually create form tables and whatnot later.

ArsenalGamesDF = pd.DataFrame(arsenal_games)
ArsenalGamesDF = ArsenalGamesDF[['Date','HomeTeam','AwayTeam','HTHG','HTAG','FTHG','FTAG','Referee']]

#add in big six status of opposition
BigSix = ['Tottenham','Liverpool','Man United','Man City','Chelsea']

for i in range(len(ArsenalGamesDF)):
    if ArsenalGamesDF.loc[i,'HomeTeam'] in BigSix or ArsenalGamesDF.loc[i,'AwayTeam'] in BigSix:
        ArsenalGamesDF.loc[i,'BigSix'] = True
    else:
        ArsenalGamesDF.loc[i,'BigSix'] = False


#add in the result
for i in range(len(ArsenalGamesDF)):
    if ArsenalGamesDF.loc[i,'HomeTeam'] == 'Arsenal':
        if ArsenalGamesDF.loc[i,'FTHG'] > ArsenalGamesDF.loc[i,'FTAG']:
            ArsenalGamesDF.loc[i,'Result'] = 'W'
        if ArsenalGamesDF.loc[i,'FTHG'] == ArsenalGamesDF.loc[i,'FTAG']:
            ArsenalGamesDF.loc[i,'Result'] = 'D'
        if ArsenalGamesDF.loc[i,'FTHG'] < ArsenalGamesDF.loc[i,'FTAG']:
            ArsenalGamesDF.loc[i,'Result'] = 'L'
    else:
        if ArsenalGamesDF.loc[i,'FTAG'] > ArsenalGamesDF.loc[i,'FTHG']:
            ArsenalGamesDF.loc[i,'Result'] = 'W'
        if ArsenalGamesDF.loc[i,'FTAG'] == ArsenalGamesDF.loc[i,'FTHG']:
            ArsenalGamesDF.loc[i,'Result'] = 'D'
        if ArsenalGamesDF.loc[i,'FTAG'] < ArsenalGamesDF.loc[i,'FTHG']:
            ArsenalGamesDF.loc[i,'Result'] = 'L'

#add in boolean for home team or not
for i in range(len(ArsenalGamesDF)):
    if ArsenalGamesDF.loc[i,'HomeTeam'] == 'Arsenal':
        ArsenalGamesDF.loc[i,'Home'] = True
    else:
        ArsenalGamesDF.loc[i,'Home'] = False

#now to try and implemenent some way to keep track of form. i'm thinking look back at the
#last five games and just create an integer of how many wins there are... not the best logic
#considering the starting and stopping of seasons but might be somewhat effective still.
#actually looking at it now im going to implement a method where a draw is worth .25 points at home, .5 away


#edit: also going to take into account big six status of other team.

win = 100
home_draw_bigsix = 0
home_loss_bigsix = -100
home_draw_ow = 0
home_loss_ow = -100
away_draw_bigsix = 0
away_loss_bigsix = -100
away_draw_ow = 0
away_loss_ow = -100

for i in range(len(ArsenalGamesDF)):
    form = 0
    for j in range(1,6):
        try:
            
            if ArsenalGamesDF.loc[i-j,'Result'] == 'W':
                form += win
            if ArsenalGamesDF.loc[i-j,'Result'] == 'D' and ArsenalGamesDF.loc[i-j,'Home'] == True and ArsenallGamesDF.loc[i-j,'BigSix'] == True:
                form += home_draw_bigsix
            if ArsenalGamesDF.loc[i-j,'Result'] == 'D' and ArsenalGamesDF.loc[i-j,'Home'] == False and ArsenalGamesDF.loc[i-j,'BigSix'] == True:
                form += away_draw_bigsix
            if ArsenalGamesDF.loc[i-j,'Result'] == 'L' and ArsenalGamesDF.loc[i-j,'Home'] == True and ArsenalGamesDF.loc[i-j,'BigSix'] == True:
                form += home_loss_bigsix
            if ArsenalGamesDF.loc[i-j,'Result'] == 'L' and ArsenalGamesDF.loc[i-j,'Home'] == False and ArsenalGamesDF.loc[i-j,'BigSix'] == True:
                form += away_loss_bigsix
            if ArsenalGamesDF.loc[i-j,'Result'] == 'L' and ArsenalGamesDF.loc[i-j,'Home'] == False and ArsenalGamesDF.loc[i-j,'BigSix'] == False:
                form += away_loss_ow
            if ArsenalGamesDF.loc[i-j,'Result'] == 'L' and ArsenalGamesDF.loc[i-j,'Home'] == True and ArsenalGamesDF.loc[i-j,'BigSix'] == False:
                form += home_loss_ow
            if ArsenalGamesDF.loc[i-j,'Result'] == 'D' and ArsenalGamesDF.loc[i-j,'Home'] == True and ArsenalGamesDF.loc[i-j,'BigSix'] == False:
                form += home_draw_ow
            if ArsenalGamesDF.loc[i-j,'Result'] == 'D' and ArsenalGamesDF.loc[i-j,'Home'] == False and ArsenalGamesDF.loc[i-j,'BigSix'] == False:
                form += away_draw_ow
        except:
            continue
    ArsenalGamesDF.loc[i,'Form'] = form

In [42]:
#we will use the terminology of 0 = loss, 1 = draw, and 3 = win (in terms of classification)

#we will also have to change the True/False to 0/1 values, as well as the big six and referee values. 

#to do this we will create a new dataframe.

ArsenalGamesDF.loc[ArsenalGamesDF.Result == 'W', 'Result'] = 3
ArsenalGamesDF.loc[ArsenalGamesDF.Result == 'D', 'Result'] = 1
ArsenalGamesDF.loc[ArsenalGamesDF.Result == 'L', 'Result'] = 0

ArsenalGamesDF.loc[ArsenalGamesDF.Home == True, 'Home'] = 1
ArsenalGamesDF.loc[ArsenalGamesDF.Home == False, 'Home'] = 0

ArsenalGamesDF.loc[ArsenalGamesDF.BigSix == True, 'BigSix'] = 1
ArsenalGamesDF.loc[ArsenalGamesDF.BigSix == False, 'BigSix'] = 0

In [43]:
#we should get rid of the very first value of the dataframe as it might mess up future results.. (no past games for form)

ArsenalGamesDF = ArsenalGamesDF.drop([0])

print(ArsenalGamesDF.head())

       Date        HomeTeam   AwayTeam  HTHG  HTAG  FTHG  FTAG     Referee  \
1  16/08/15  Crystal Palace    Arsenal     1     1     1     2     L Mason
2  24/08/15         Arsenal  Liverpool     0     0     0     0    M Oliver
3  29/08/15       Newcastle    Arsenal     0     0     0     1  A Marriner
4  12/09/15         Arsenal      Stoke     1     0     2     0      J Moss
5  19/09/15         Chelsea    Arsenal     0     0     2     0      M Dean

  BigSix Result Home   Form
1      0      3    0 -100.0
2      1      1    1 -100.0
3      0      3    0 -100.0
4      0      3    1 -100.0
5      1      0    0 -100.0

In [44]:
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [45]:
#for the basic model, im lazy and will get rid of the referee.. oops. we'll revisit that.

#lets get only the columns we want, and in a certain order as well.

ArsenalGamesDF = ArsenalGamesDF.drop(columns = ['Date','HomeTeam','AwayTeam','HTHG','HTAG','FTHG','FTAG','Referee'])

ArsenalGamesDF = ArsenalGamesDF[['Home', 'BigSix', 'Form', 'Result']]

print(ArsenalGamesDF.head())

  Home BigSix   Form Result
1    0      0 -100.0      3
2    1      1 -100.0      1
3    0      0 -100.0      3
4    1      0 -100.0      3
5    0      1 -100.0      0

In [46]:
#we need to split up this dataframe into training and testing
y = ArsenalGamesDF['Result']
ArsenalGamesDF = ArsenalGamesDF.drop(columns = ['Result'])
X_train, X_test, y_train, y_test = train_test_split(ArsenalGamesDF, y, test_size=0.125,shuffle = False)
y_train = y_train.astype('int')

In [47]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
print(y_train)
print(X_train)
predictions = gnb.fit(X_train, y_train).predict(X_test)

1      3
2      1
3      3
4      3
5      0
      ..
261    3
262    1
263    3
264    3
265    3
Name: Result, Length: 265, dtype: int64
    Home BigSix   Form
1      0      0 -100.0
2      1      1 -100.0
3      0      0 -100.0
4      1      0 -100.0
5      0      1 -100.0
..   ...    ...    ...
261    0      0    0.0
262    1      1    0.0
263    0      0    0.0
264    1      0    0.0
265    0      0    0.0

[265 rows x 3 columns]

In [48]:
predictions[0:5]

array([3, 1, 0, 3, 3])

In [49]:
print(type(X_test))

<class 'pandas.core.frame.DataFrame'>

In [50]:
print(type(y_test))

<class 'pandas.core.series.Series'>

In [51]:
print(type(predictions))

<class 'numpy.ndarray'>

In [52]:
bayes_results = pd.DataFrame(X_test)

In [53]:
bayes_results['ActualResult'] = y_test

In [54]:
bayes_results['Prediction'] = predictions

In [55]:
bayes_results.head()

    Home BigSix   Form ActualResult  Prediction
266    0      0    0.0            1           3
267    1      1    0.0            0           1
268    0      1 -100.0            0           0
269    1      0 -200.0            3           3
270    0      0 -200.0            0           3

In [56]:
bayes_results.loc[bayes_results.ActualResult == bayes_results.Prediction, 'Correct'] = 'Yes'

In [57]:
bayes_results.loc[bayes_results.ActualResult != bayes_results.Prediction, 'Correct'] = 'No'

In [58]:
bayes_results

    Home BigSix   Form ActualResult  Prediction Correct
266    0      0    0.0            1           3      No
267    1      1    0.0            0           1      No
268    0      1 -100.0            0           0     Yes
269    1      0 -200.0            3           3     Yes
270    0      0 -200.0            0           3      No
271    1      0 -300.0            3           3     Yes
272    0      1 -300.0            0           0     Yes
273    1      0 -300.0            3           3     Yes
274    1      0 -200.0            3           3     Yes
275    0      1 -200.0            3           0      No
276    1      0 -100.0            3           3     Yes
277    0      0 -100.0            3           3     Yes
278    1      0    0.0            1           3      No
279    0      0    0.0            3           3     Yes
280    1      0    0.0            3           3     Yes
281    0      1    0.0            0           0     Yes
282    0      0 -100.0            3           3     Yes
283    1      0 -100.0            1           3      No
284    1      0 -100.0            3           3     Yes
285    0      0 -100.0            0           3      No
286    0      0 -200.0            0           3      No
287    1      1 -200.0            0           1      No
288    0      0 -300.0            1           3      No
289    1      0 -300.0            3           3     Yes
290    0      0 -300.0            3           3     Yes
291    1      1 -200.0            3           1      No
292    0      1 -100.0            3           0      No
293    1      0    0.0            3           3     Yes
294    0      0    0.0            3           3     Yes
295    1      0    0.0            3           3     Yes
296    0      0    0.0            0           3      No
297    1      1 -100.0            3           1      No
298    0      0 -100.0            3           3     Yes
299    1      0 -100.0            0           3      No
300    1      1 -200.0            1           1     Yes
301    0      0 -200.0            1           3      No
302    1      0 -100.0            1           3      No
303    0      0 -100.0            3           3     Yes

In [59]:
num_correct = len(bayes_results[bayes_results['Correct'] == 'Yes'])

print('Predicted {} out of {}. {}%'.format(num_correct,len(bayes_results),100*num_correct/len(bayes_results)))

Predicted 21 out of 38. 55.26315789473684%

In [60]:
print(sum(bayes_results['Prediction']))

89